pystol-ui/app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

pystol-ui/app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

pystol-ui/app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

pystol-ui/app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)
from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

from app.base.k8s import list_actions, show_actions
from app.base.k8sclient import  state_namespaces, state_nodes, state_pods, web_terminal, cluster_name_configured

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))


## API endpoints

@blueprint.route('/api/v1/ListActions', methods=['GET'])
def api_list_actions():
    return jsonify(list_actions())

@blueprint.route('/api/v1/ShowActions', methods=['GET'])
def api_show_actions():
    return jsonify(show_actions())

@blueprint.route('/api/v1/StateNamespaces', methods=['GET'])
def api_state_namespaces():
    return jsonify(state_namespaces())

@blueprint.route('/api/v1/StateNodes', methods=['GET'])
def api_state_nodes():
    return jsonify(state_nodes())

@blueprint.route('/api/v1/StatePods', methods=['GET'])
def api_state_pods():
    return jsonify(state_pods())

@blueprint.route('/api/v1/Terminal', methods=['GET'])
def api_web_terminal():
    return jsonify(web_terminal())

@blueprint.route('/api/v1/ClusterName', methods=['GET'])
def api_cluster_name_configured():
    return jsonify(cluster_name_configured())

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    # return render_template('errors/403.html'), 403
    return render_template('page-403.html', template_folder="../home/templates/"), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    # return render_template('errors/403.html'), 403
    return render_template('page-403.html', template_folder="../home/templates/"), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    # return render_template('errors/404.html'), 404
    return render_template('page-404.html', template_folder="../home/templates/"), 404

@blueprint.errorhandler(500)
def internal_error(error):
    # return render_template('errors/500.html'), 500
    return render_template('page-500.html', template_folder="../home/templates/"), 500

pystol-ui/app/base/templates/base-site-fullscreen.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="Pystol.org - The fault injection platform">
    <meta name="author" content="pystol.org (@pystol)">
    <meta name="keyword" content="Pystol,Fault injection,Chaos engineering">
    
    <title>
        Pystol.org - {% block title %}{% endblock %}
    </title>

    <!-- Begin icons-->
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/static/assets/favicon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/favicon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/favicon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/favicon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/static/assets/favicon/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/static/assets/favicon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/static/assets/favicon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/static/assets/favicon/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-128.png" sizes="128x128" />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/static/assets/favicon/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/static/assets/favicon/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/static/assets/favicon/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/static/assets/favicon/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/static/assets/favicon/mstile-310x310.png" />
    <meta name="theme-color" content="#ffffff">
    <!-- End icons-->

    <!-- Icons-->
    <link href="/static/assets/vendors/@coreui/icons/css/free.min.css" rel="stylesheet">
    <link href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">

    <!-- Main styles for this application-->
    <link href="/static/assets/css/style.css" rel="stylesheet">
    <link href="/static/assets/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

    <!-- Specific Page CSS goes HERE  -->  
    {% block stylesheets %}{% endblock stylesheets %}

  </head>
  <body class="c-app flex-row align-items-center">

    <div class="container">

        {% block content %}{% endblock content %}
    
    </div>

    {% include 'site_template/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

  </body>
</html>

pystol-ui/app/base/templates/base-site.html
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v3.0.0-alpha.1
* @link https://coreui.io
* Copyright (c) 2019 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="Pystol.org - The fault injection platform">
    <meta name="author" content="pystol.org (@pystol)">
    <meta name="keyword" content="Pystol,Fault injection,Chaos engineering">

{% set titl %}
{% block title %}{% endblock %}
{% endset %}

    <title>
        Pystol.org - {{ titl }}
    </title>


    <!-- Begin icons-->
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="/static/assets/favicon/apple-touch-icon-57x57.png" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/favicon/apple-touch-icon-114x114.png" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/favicon/apple-touch-icon-72x72.png" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/favicon/apple-touch-icon-144x144.png" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="/static/assets/favicon/apple-touch-icon-60x60.png" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="/static/assets/favicon/apple-touch-icon-120x120.png" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="/static/assets/favicon/apple-touch-icon-76x76.png" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="/static/assets/favicon/apple-touch-icon-152x152.png" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-196x196.png" sizes="196x196" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-16x16.png" sizes="16x16" />
    <link rel="icon" type="image/png" href="/static/assets/favicon/favicon-128.png" sizes="128x128" />
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="/static/assets/favicon/mstile-144x144.png" />
    <meta name="msapplication-square70x70logo" content="/static/assets/favicon/mstile-70x70.png" />
    <meta name="msapplication-square150x150logo" content="/static/assets/favicon/mstile-150x150.png" />
    <meta name="msapplication-wide310x150logo" content="/static/assets/favicon/mstile-310x150.png" />
    <meta name="msapplication-square310x310logo" content="/static/assets/favicon/mstile-310x310.png" />
    <meta name="theme-color" content="#ffffff">
    <!-- End icons-->

    <!-- Icons-->
    <link href="/static/assets/vendors/@coreui/icons/css/free.min.css" rel="stylesheet">
    <link href="/static/assets/vendors/@coreui/icons/css/brand.min.css" rel="stylesheet">
    <link href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">

    <!-- Main styles for this application-->
    <link href="/static/assets/css/style.css" rel="stylesheet">
    <link href="/static/assets/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

    <link href="/static/assets/vendors/@coreui/coreui-chartjs/css/coreui-chartjs.css" rel="stylesheet">

    <!-- Specific Page CSS goes HERE  -->
    {% block stylesheets %}{% endblock stylesheets %}

  </head>
  <body class="c-app">

    {% include 'site_template/sidebar.html' %}

    <div class="c-wrapper">

{% with title=titl %}
      {% include 'site_template/navigation.html' %}
{% endwith %}

      <div class="c-body">
        <main class="c-main">

          {% block content %}{% endblock content %}

        </main>
      </div>

      {% include 'site_template/footer.html' %}

    </div>

    {% include 'site_template/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

  </body>
</html>

pystol-ui/app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card-group">
          <div class="card p-4">
          
            <form role="form" method="post" action="">

              {{ form.hidden_tag() }} 

              <div class="card-body">

                <div class="text-center">
<h1>
                  <a href="https://www.pystol.org" target="_blank"><img class="c-header-brand" src="/static/assets/brand/pystol-base.svg" width="97" height="46" alt="Pystol"></a>
</h1>
                  <h5>Login</h5>
                  <p class="text-muted">
                    {% if msg %}
                      {{ msg | safe }}
                    {% else %}
                    <span>
                      Use default credentials: <strong>asdf / asdf</strong>
                      <br />
                      OR <a href={{ url_for('base_blueprint.create_user') }} >create your own user</a>
                    </span>
                    {% endif %}

                  </p>
                </div>

                <br />

                <div class="input-group mb-3">
                  <div class="input-group-prepend"><span class="input-group-text">
                      <svg class="c-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                      </svg></span></div>
                  {{ form.username(placeholder="Username", class="form-control") }}
                </div>

                <div class="input-group mb-4">
                  <div class="input-group-prepend"><span class="input-group-text">
                      <svg class="c-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                      </svg></span></div>
                  {{ form.password(placeholder="Password", class="form-control", type="password") }}
                </div>

                <br />

                <div class="text-center">
                    <button type="submit" name="login" class="btn btn-primary px-4">Login</button>
                </div>

              </div>
            
            </form>  

            <div class="card-footer p-4 text-center">
                Don't have an account? <a href={{ url_for('base_blueprint.create_user') }} >Register</a>
            </div>
              
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

pystol-ui/app/base/templates/site_template/footer.html
<footer class="c-footer">
    <div><a href="https://github.com/pystol/pystol/tree/master/pystol-ui">The Pystol dashboard</a></div>
    <div class="ml-auto"><a href="https://www.pystol.org/">Pystol.org</a> The fault injection platform</div>
</footer>

pystol-ui/app/base/templates/site_template/navigation.html
      <header class="c-header c-header-light c-header-fixed">

            <button class="c-header-toggler c-class-toggler d-lg-none mr-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
                <span class="c-header-toggler-icon"></span>
            </button>
            <a class="c-header-brand d-sm-none" href="#"><img class="c-header-brand" src="/static/assets/brand/pystol-base.svg" width="97" height="46" alt="Pystol"></a>
            <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
                <span class="c-header-toggler-icon"></span>
            </button>
            <ul class="c-header-nav d-md-down-none">
              <li class="breadcrumb-item">{{ title }}</li>
            </ul>
            <ul class="c-header-nav ml-auto mr-4">
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="https://github.com/pystol/" target="_blank">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/brand.svg#cib-github"></use>
                  </svg>
                  </a>
              </li>
              <li class="c-header-nav-item d-md-down-none mx-2">
                  <a class="c-header-nav-link" href="https://docs.pystol.org/" target="_blank">
                    <svg class="c-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-book"></use>
                    </svg>
                  </a>
              </li>
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="{{ url_for('base_blueprint.logout') }}">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg></a>
              </li>
            </ul>
          </header>

pystol-ui/app/base/templates/site_template/scripts.html
    <!-- CoreUI and necessary plugins-->
    <script src="/static/assets/vendors/pace-progress/js/pace.min.js"></script>
    <script src="/static/assets/vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>

pystol-ui/app/base/templates/site_template/sidebar.html
    <div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
            <div class="c-sidebar-brand"><img class="c-sidebar-brand-full" src="/static/assets/brand/pystol_full.svg" width="118" height="46" alt="CoreUI Logo"><img class="c-sidebar-brand-minimized" src="/static/assets/brand/pystol_compact.svg" width="118" height="46" alt="CoreUI Logo"></div>
            <ul class="c-sidebar-nav">
              <li class="c-sidebar-nav-title">Cluster status</li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/index">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                  </svg> System information</a>

                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-actions-namespaces">
                    <svg class="c-sidebar-nav-icon">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                    </svg> Namespaces</a></li>

                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-actions-nodes">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                      </svg> Nodes</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-actions-pods">
                        <svg class="c-sidebar-nav-icon">
                          <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                        </svg> Pods</a></li>
              </li>
              <li class="c-sidebar-nav-title">Pystol</li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-actions-executed">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                  </svg> Actions executed</a>
              </li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-actions-available">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                  </svg> Actions available</a>
              </li>

              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-update-kubeconfig">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                  </svg> Change cluster</a>
              </li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/pystol-client-cluster">
                <svg class="c-sidebar-nav-icon">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-arrow-right"></use>
                </svg>Client Pystol in cluster</a>
              </li>

              <li class="c-sidebar-nav-item px-3 c-d-compact-none c-d-minimized-none mt-auto">
                  <div class="text-uppercase mb-1">
                  <small>
                {% if cluster_name_configured |length %}
                      <span class="badge badge-success">Connected to {{cluster_name_configured  | replace('[', '')| replace(']', '')}}</span>
                {% else %}
                      <span class="badge badge-danger">Not connected</span>
                {% endif %}
                  </small></div>
              </li>

<!--               <li class="c-sidebar-nav-item px-3 c-d-compact-none c-d-minimized-none">
                  <div class="text-uppercase mb-1"><small><b>Pods Usage</b></small></div>
                  <div class="progress progress-xs">
                  <div class="progress-bar bg-info" role="progressbar" style="width: {{ compute_allocated_resources.pods.percentage }}%" aria-valuenow="{{ compute_allocated_resources.pods.percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
                  {% set pods_allocated = compute_allocated_resources.pods.allocated.magnitude | int %}
                  {% set pods_allocatable = compute_allocated_resources.pods.allocatable.magnitude | int %}
                  {% set pods_unit = compute_allocated_resources.pods.allocatable.units %}
                  </div><small class="text-muted">{{ pods_allocated }}/{{ pods_allocatable }} {{ pods_unit }}</small>
              </li>

              <li class="c-sidebar-nav-item px-3 c-d-compact-none c-d-minimized-none">
                  <div class="text-uppercase mb-1"><small><b>CPU usage</b></small></div>
                  <div class="progress progress-xs">
                  <div class="progress-bar bg-success" role="progressbar" style="width: {{ compute_allocated_resources.cpu.percentage }}%" aria-valuenow="{{ compute_allocated_resources.cpu.percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
                  {% set cpu_allocated = compute_allocated_resources.cpu.allocated.magnitude | int %}
                  {% set cpu_allocatable = compute_allocated_resources.cpu.allocatable.magnitude | int %}
                  {% set cpu_unit = compute_allocated_resources.cpu.allocatable.units %}
                  </div><small class="text-muted">{{ cpu_allocated }}/{{ cpu_allocatable }} {{ cpu_unit }}</small>
              </li>

              <li class="c-sidebar-nav-item px-3 c-d-compact-none c-d-minimized-none">
                  <div class="text-uppercase mb-1"><small><b>Memory Usage</b></small></div>
                  <div class="progress progress-xs">
                  <div class="progress-bar bg-warning" role="progressbar" style="width: {{ compute_allocated_resources.mem.percentage }}%" aria-valuenow="{{ compute_allocated_resources.mem.percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
                  {% set mem_allocated = compute_allocated_resources.mem.allocated.magnitude | int %}
                  {% set mem_allocatable = compute_allocated_resources.mem.allocatable.magnitude | int %}
                  {% set mem_unit = compute_allocated_resources.mem.allocatable.units %}
                  </div><small class="text-muted">{{ mem_allocated }}/{{ mem_allocatable }} {{ mem_unit}}</small>
              </li>

              <li class="c-sidebar-nav-item px-3 mb-3 c-d-compact-none c-d-minimized-none">
                  <div class="text-uppercase mb-1"><small><b>Filesystem</b></small></div>
                  <div class="progress progress-xs">
                  <div class="progress-bar bg-danger" role="progressbar" style="width: {{ compute_allocated_resources.storage.percentage }}%" aria-valuenow="{{ compute_allocated_resources.storage.percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
                  {% set storage_allocated = compute_allocated_resources.storage.allocated.magnitude | int %}
                  {% set storage_allocatable = compute_allocated_resources.storage.allocatable.magnitude | int %}
                  {% set storage_unit = compute_allocated_resources.storage.allocatable.units %}
                  </div><small class="text-muted">{{ storage_allocated }}/{{ storage_allocatable }} {{ storage_unit}}</small>
              </li> -->



              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/about-pystol">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-heart"></use>
                  </svg> F.A.Q.</a>
              </li>


              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href={{ url_for('base_blueprint.logout') }} >
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg> Logout</a>
              </li>




            </ul>
            <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
          </div>